repos:
  - repo: local
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
